#!/usr/bin/env bash
set -Eeuo pipefail

SERVICE_NAME="vps-monitor-agent"
NATIVE_DIR="/opt/vps-monitor-agent"
DEFAULT_AGENT_IMAGE="${VPS_MONITOR_AGENT_IMAGE:-vps-monitor-agent:latest}"
# Default release repository used by the short native installer command.
DEFAULT_RELEASE_REPO="${VPS_MONITOR_AGENT_RELEASE_REPO:-mghts/vps-monitor}"
DEFAULT_RELEASE_TAG="${VPS_MONITOR_AGENT_RELEASE_TAG:-latest}"

ACTION="install"
MODE="native"
ENDPOINT=""
TOKEN=""
AGENT_IMAGE="$DEFAULT_AGENT_IMAGE"
DOCKER_PLATFORM=""
RELEASE_REPO="$DEFAULT_RELEASE_REPO"
RELEASE_TAG="$DEFAULT_RELEASE_TAG"
ASSET_BASE_URL=""
PUBLIC_IP=""

usage() {
  cat <<'USAGE'
VPS Monitor Agent installer

Usage:
  install.sh -e <center-url> -t <agent-token> [options]
  install.sh uninstall [-m native|docker|all]

Install options:
  -e, --endpoint       Center URL, for example https://monitor.example.com
  -t, --token          Agent token generated by the admin panel
  -m, --mode           Install mode: native or docker. Default: native
  -r, --repo           GitHub repository for release assets, for example owner/vps-monitor
      --tag            GitHub release tag. Default: latest
      --asset-base-url Download base URL for release assets. Overrides --repo/--tag
  -i, --image          Docker Agent image. Used only with -m docker
  -p, --platform       Docker image platform. Default: auto-detect from uname -m
      --public-ip      Optional public IP override reported by Agent
  -h, --help           Show help

Examples:
  wget -qO- https://raw.githubusercontent.com/mghts/vps-monitor/refs/heads/main/agent/install.sh | sudo bash -s -- -e https://monitor.example.com -t TOKEN
  wget -qO- https://raw.githubusercontent.com/mghts/vps-monitor/refs/heads/main/agent/install.sh | sudo bash -s -- -e https://monitor.example.com -t TOKEN -m docker -i your-dockerhub-user/vps-monitor-agent:latest
USAGE
}

if [ "${1:-}" = "uninstall" ] || [ "${1:-}" = "remove" ]; then
  ACTION="uninstall"
  shift
fi

while [ "$#" -gt 0 ]; do
  case "$1" in
    -e|--endpoint)
      ENDPOINT="${2:-}"
      shift 2
      ;;
    -t|--token)
      TOKEN="${2:-}"
      shift 2
      ;;
    -m|--mode)
      MODE="${2:-}"
      shift 2
      ;;
    -r|--repo)
      RELEASE_REPO="${2:-}"
      shift 2
      ;;
    --tag)
      RELEASE_TAG="${2:-}"
      shift 2
      ;;
    --asset-base-url)
      ASSET_BASE_URL="${2:-}"
      shift 2
      ;;
    -i|--image)
      AGENT_IMAGE="${2:-}"
      shift 2
      ;;
    -p|--platform)
      DOCKER_PLATFORM="${2:-}"
      shift 2
      ;;
    --public-ip)
      PUBLIC_IP="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "未知参数：$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

ENDPOINT="${ENDPOINT%/}"
ASSET_BASE_URL="${ASSET_BASE_URL%/}"

if [ "$(id -u)" -ne 0 ]; then
  echo "请使用 sudo 或 root 权限运行安装脚本。" >&2
  exit 1
fi

install_dependencies() {
  if command -v curl >/dev/null 2>&1 && command -v ping >/dev/null 2>&1; then
    return
  fi
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update
    apt-get install -y curl ca-certificates iputils-ping
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y curl ca-certificates iputils
  elif command -v yum >/dev/null 2>&1; then
    yum install -y curl ca-certificates iputils
  elif command -v apk >/dev/null 2>&1; then
    apk add --no-cache curl ca-certificates iputils
  else
    echo "缺少 curl 或 ping，且未找到可支持的包管理器。" >&2
    exit 1
  fi
}

download_file() {
  url="$1"
  dest="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$dest"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$dest" "$url"
  else
    echo "缺少 curl/wget，无法下载文件。" >&2
    exit 1
  fi
}

verify_sha256() {
  file="$1"
  checksum_file="$2"
  expected="$(awk '{print $1}' "$checksum_file" | head -n 1)"
  if [ -z "$expected" ]; then
    echo "Agent 校验文件为空，已中止安装。" >&2
    exit 1
  fi
  if command -v sha256sum >/dev/null 2>&1; then
    actual="$(sha256sum "$file" | awk '{print $1}')"
  elif command -v shasum >/dev/null 2>&1; then
    actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  else
    echo "系统缺少 sha256sum/shasum，无法验证 Agent 完整性。" >&2
    exit 1
  fi
  if [ "$actual" != "$expected" ]; then
    echo "Agent SHA-256 校验失败，已中止安装。" >&2
    exit 1
  fi
}

detect_docker_platform() {
  if [ -n "$DOCKER_PLATFORM" ]; then
    echo "$DOCKER_PLATFORM"
    return
  fi
  case "$(uname -m)" in
    x86_64|amd64)
      echo "linux/amd64"
      ;;
    aarch64|arm64)
      echo "linux/arm64"
      ;;
    armv7l|armv7*)
      echo "linux/arm/v7"
      ;;
    *)
      echo "无法识别当前 CPU 架构：$(uname -m)，请使用 --platform 手动指定。" >&2
      exit 1
      ;;
  esac
}

detect_native_asset() {
  case "$(uname -m)" in
    x86_64|amd64)
      echo "amd64|vps-monitor-agent-linux-amd64"
      ;;
    aarch64|arm64)
      echo "arm64|vps-monitor-agent-linux-arm64"
      ;;
    armv7l|armv7*)
      echo "armv7|vps-monitor-agent-linux-armv7"
      ;;
    *)
      echo "无法识别当前 CPU 架构：$(uname -m)，无法选择 Agent 二进制。" >&2
      exit 1
      ;;
  esac
}

release_asset_url() {
  asset="$1"
  if [ -n "$ASSET_BASE_URL" ]; then
    echo "$ASSET_BASE_URL/$asset"
    return
  fi
  if [ -z "$RELEASE_REPO" ]; then
    echo "缺少 GitHub Releases 仓库，请使用 -r owner/repo，或在脚本中设置 VPS_MONITOR_AGENT_RELEASE_REPO。" >&2
    exit 1
  fi
  if [ "$RELEASE_TAG" = "latest" ] || [ -z "$RELEASE_TAG" ]; then
    echo "https://github.com/$RELEASE_REPO/releases/latest/download/$asset"
  else
    echo "https://github.com/$RELEASE_REPO/releases/download/$RELEASE_TAG/$asset"
  fi
}

install_native() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "非 Docker 版需要 systemd/systemctl，当前系统不支持。" >&2
    exit 1
  fi
  install_dependencies
  asset_selection="$(detect_native_asset)"
  native_arch="${asset_selection%%|*}"
  asset_name="${asset_selection#*|}"
  asset_url="$(release_asset_url "$asset_name")"
  tmp_file="$(mktemp)"
  checksum_file="$(mktemp)"
  trap 'rm -f "$tmp_file" "$checksum_file"' EXIT

  echo "检测到 native 架构：$native_arch"
  echo "下载 Agent 二进制：$asset_url"
  download_file "$asset_url" "$tmp_file"
  download_file "${asset_url}.sha256" "$checksum_file"
  verify_sha256 "$tmp_file" "$checksum_file"

  install -d -m 0755 "$NATIVE_DIR"
  install -m 0755 "$tmp_file" "$NATIVE_DIR/vps-monitor-agent"
  cat >"$NATIVE_DIR/agent.env" <<EOF
VPS_MONITOR_SERVER_URL=$ENDPOINT
VPS_MONITOR_AGENT_TOKEN=$TOKEN
VPS_MONITOR_HOST_ROOT=/
RUST_LOG=info
EOF
  if [ -n "$PUBLIC_IP" ]; then
    printf 'VPS_MONITOR_PUBLIC_IP=%s\n' "$PUBLIC_IP" >>"$NATIVE_DIR/agent.env"
  fi
  chmod 0600 "$NATIVE_DIR/agent.env"
  cat >/etc/systemd/system/$SERVICE_NAME.service <<EOF
[Unit]
Description=VPS Monitor Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$NATIVE_DIR/agent.env
ExecStart=$NATIVE_DIR/vps-monitor-agent
Restart=always
RestartSec=5
User=nobody
AmbientCapabilities=CAP_NET_RAW
CapabilityBoundingSet=CAP_NET_RAW
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now "$SERVICE_NAME"
  systemctl restart "$SERVICE_NAME"
  echo "VPS Monitor Agent systemd 版安装完成。"
}

install_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "未检测到 docker，请先安装 Docker 后重试。" >&2
    exit 1
  fi
  platform="$(detect_docker_platform)"
  echo "检测到 Docker 平台：$platform"
  echo "拉取 Agent 镜像：$AGENT_IMAGE"
  docker pull --platform "$platform" "$AGENT_IMAGE"
  docker rm -f "$SERVICE_NAME" >/dev/null 2>&1 || true
  docker_env_args=()
  if [ -n "$PUBLIC_IP" ]; then
    docker_env_args=(-e "VPS_MONITOR_PUBLIC_IP=$PUBLIC_IP")
  fi
  docker run -d \
    --name "$SERVICE_NAME" \
    --platform "$platform" \
    --restart unless-stopped \
    --read-only \
    --tmpfs /tmp:rw,noexec,nosuid,size=16m \
    --cap-drop ALL \
    --cap-add NET_RAW \
    --security-opt no-new-privileges:true \
    -v /etc/hostname:/host/etc/hostname:ro \
    -v /etc/os-release:/host/etc/os-release:ro \
    -v /proc/net/dev:/host/proc/net/dev:ro \
    -e VPS_MONITOR_SERVER_URL="$ENDPOINT" \
    -e VPS_MONITOR_AGENT_TOKEN="$TOKEN" \
    -e VPS_MONITOR_HOST_ROOT=/host \
    "${docker_env_args[@]}" \
    "$AGENT_IMAGE"
  echo "VPS Monitor Agent Docker 版安装完成。"
}

uninstall_native() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable --now "$SERVICE_NAME" >/dev/null 2>&1 || true
    rm -f "/etc/systemd/system/$SERVICE_NAME.service"
    systemctl daemon-reload || true
  fi
  rm -rf "$NATIVE_DIR"
}

uninstall_docker() {
  if command -v docker >/dev/null 2>&1; then
    docker rm -f "$SERVICE_NAME" >/dev/null 2>&1 || true
  fi
}

if [ "$ACTION" = "uninstall" ]; then
  case "$MODE" in
    native|systemd)
      uninstall_native
      ;;
    docker)
      uninstall_docker
      ;;
    all)
      uninstall_docker
      uninstall_native
      ;;
    *)
      echo "卸载模式只能是 native、docker 或 all。" >&2
      exit 1
      ;;
  esac
  echo "VPS Monitor Agent 卸载完成。"
  exit 0
fi

if [ -z "$ENDPOINT" ]; then
  echo "缺少中心端地址，请使用 -e <center-url>。" >&2
  exit 1
fi

if [ -z "$TOKEN" ]; then
  echo "缺少 Agent token，请使用 -t <agent-token>。" >&2
  exit 1
fi

case "$ENDPOINT" in
  https://*) ;;
  http://127.0.0.1*|http://localhost*|http://\[::1\]*) ;;
  *)
    echo "中心端地址必须使用 HTTPS（仅本机回环地址允许 HTTP）。" >&2
    exit 1
    ;;
esac

if [ "${#TOKEN}" -lt 32 ] || [ "${#TOKEN}" -gt 512 ]; then
  echo "Agent token 长度不合法。" >&2
  exit 1
fi

if [ "$MODE" = "docker" ] && [[ "$AGENT_IMAGE" == -* ]]; then
  echo "Agent 镜像名称不合法。" >&2
  exit 1
fi

case "$MODE" in
  native|systemd)
    install_native
    ;;
  docker)
    install_docker
    ;;
  *)
    echo "安装模式只能是 native 或 docker。" >&2
    exit 1
    ;;
esac
